name: dadjokes
description: A collection of terrible jokes.

dependencies:
  flutter:
    sdk: flutter
  http: "^0.12.0"
  share: "^0.4.0"
  auto_size_text: ^0.2.0

flutter:
  uses-material-design: true
  assets:
   - assets/icon.png
  fonts:
    - family: Patrick Hand
      fonts:
       - asset: assets/fonts/PatrickHand-Regular.ttf
