name: dadjokes
version: 1.2.0
description: A collection of terrible jokes.

dependencies:
  flutter:
    sdk: flutter
  http: "^0.12.0"
  share: "^0.5.3"
  auto_size_text: "^0.2.1"

flutter:
  uses-material-design: true
  assets:
   - assets/icon.png
  fonts:
    - family: Patrick Hand
      fonts:
       - asset: assets/fonts/PatrickHand-Regular.ttf
